---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Check ansible_kernel
      debug:
        msg: "{{ ansible_kernel }}"

    - name: Fix SystemD on docker images within Windows WSL
      when: '"microsoft" in ansible_kernel'
      block:
        - name: Run "apt-get update" | Ubuntu
          apt:
            update_cache: true
          when:
            - ansible_os_family == "Debian"

        - name: Make sure python is installed | WSL
          package:
            name: python

        - name: Download systemctl.py file | WSL
          get_url:
            url: "https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py"
            dest: "/usr/bin/systemctl"
            owner: root
            group: root
            mode: "u=rwx,g=rx,o=rx"

        - name: Ensure run directory exists for ansible check_systemd | WSL
          file:
            name: /run/systemd/system/
            state: directory
            owner: root
            group: root
            mode: "u=rwX,g=rX,o=rX"

        - name: Stop D-Bus service | WSL
          service:
            name: dbus.service
            state: stopped
